apiVersion: apps/v1
kind: Deployment
metadata:
  name: tgapi
spec:
  selector:
    matchLabels:
      app: tgapi
  template:
    metadata:
      labels:
        app: tgapi
    spec:
      restartPolicy: Always
      containers:
        - name: tgapi
          resources:
            requests:
              cpu: 100m
              memory: 250Mi
            limits:
              cpu: 1
              memory: 500Mi
          image: tgapi
          imagePullPolicy: IfNotPresent
          command: ["/tgapi", "run"]
          ports:
            - name: http
              containerPort: 3000
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 3
            periodSeconds: 3
