---
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    labels:
      - "dependencies"
      - "go"
      - "type::chore"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      security:
        update-types:
          - "patch"
      k8s.io:
        patterns:
          - "k8s.io/*"
      aws-sdk-go-v2:
        patterns:
          - "github.com/aws/aws-sdk-go-v2*"

  - package-ecosystem: "npm"
    directory: "/web"
    labels:
      - "dependencies"
      - "javascript"
      - "type::chore"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    groups:
      security:
        update-types:
          - "patch"
      babel:
        patterns:
          - "@babel/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependencies"
      - "github-actions"
      - "type::chore"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
