apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  name: clusternode
spec:
  database: testgrid-postgres
  name: clusternode
  schema:
    postgres:
      primaryKey: [id]
      indexes:
        - name: idx_testinstance_id
          columns:
            - testinstance_id
      columns:
        - name: id
          type: varchar(255)
        - name: testinstance_id
          type: varchar(255)
        - name: node_type
          type: varchar(255)
        - name: status
          type: varchar(255) #status will be pending|created|waitingJoinCommand|joined
        - name: output
          type: text
        - name: created_at
          type: timestamp without timezone
