apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  name: testinstance
spec:
  database: testgrid-postgres
  name: testinstance
  schema:
    postgres:
      primaryKey: [id]
      indexes:
        - name: idx_priority
          columns:
            - priority desc
            - enqueued_at asc
      columns:
        - name: id
          type: varchar(255)
        - name: testrun_ref
          type: varchar(255)
        - name: test_id
          type: varchar(255)
        - name: test_name
          type: varchar(255)
        - name: priority
          type: int
          default: "0"
          constraints:
            notNull: true
        - name: enqueued_at
          type: timestamp without timezone
        - name: dequeued_at
          type: timestamp without timezone
        - name: started_at
          type: timestamp without timezone
        - name: running_at
          type: timestamp without timezone
        - name: finished_at
          type: timestamp without timezone
        - name: is_success
          type: boolean
        - name: failure_reason
          type: varchar(255)
        - name: is_unsupported
          type: boolean
        - name: is_skipped
          type: boolean
        - name: output
          type: text
        - name: sonobuoy_results
          type: text
        - name: kurl_yaml
          type: text
        - name: kurl_url
          type: text
        - name: kurl_flags
          type: text
        - name: upgrade_yaml
          type: text
        - name: upgrade_url
          type: text
        - name: supportbundle_yaml
          type: text
        - name: post_install_script
          type: text
        - name: post_upgrade_script
          type: text
        - name: os_name
          type: text
        - name: os_version
          type: text
        - name: os_image
          type: text
        - name: os_preinit
          type: text
        - name: primary_join_command
          type: text
        - name: secondary_join_command
          type: text
        - name: num_primary_nodes
          type: int
        - name: num_secondary_nodes
          type: int
        - name: memory
          type: varchar(11)
        - name: cpu
          type: varchar(11)
