apiVersion: apps/v1
kind: Deployment
metadata:
  name: tgapi
spec:
  replicas: 3
  template:
    spec:
      nodeSelector:
        replicated/node-pool: privileged
      containers:
        - name: tgapi
          image: 923411875752.dkr.ecr.us-east-1.amazonaws.com/tgapi
          envFrom:
            - secretRef:
                name: tgapi
          resources:
            requests:
              cpu: 100m
              memory: 750Mi
            limits:
              cpu: 1
              memory: 750Mi
          env:
            - name: AWS_REGION
              value: us-east-1
            - name: PROJECT_NAME
              value: "kurl"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: testgrid-postgres
                  key: uri
            - name: SUPPORT_BUNDLE_BUCKET
              value: "testgrid-bundles-staging"
            - name: GOMEMLIMIT
              value: 500MiB
