apiVersion: apps/v1
kind: Deployment
metadata:
  name: tgapi
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: tgapi
          image: 923411875752.dkr.ecr.us-east-1.amazonaws.com/tgapi
          env:
            - name: AWS_REGION
              value: us-east-1
            - name: PROJECT_NAME
              value: "kurl"
            - name: USE_EC2_PARAMETERS
              value: "1"