apiVersion: v1
kind: Pod
metadata:
  name: tgrun
  labels:
    app: testgrid
spec:
  containers:
  - name: tgrun
    image: replicated/tgrun
    args: ["run", "--testgrid-api", "https://api.testgrid.kurl.sh"]
  restartPolicy: OnFailure
