apiVersion: databases.schemahero.io/v1alpha4
kind: Database
metadata:
  name: testgrid-postgres
spec:
  immediateDeploy: true
  connection:
    postgres:
      uri:
        valueFrom:
          secretKeyRef:
            key: uri
            name: testgrid-postgres