apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: testgrid-postgres
  namespace: default
spec:
  encryptedData:
    uri: AgBXR/9QncAGQJ5CaaQ9DD7Kr4D7Rnlo5U7lFjuK7LvgwZ1KbgZYArkR27jQYLH2tsSKGSjefhkJjte04LeXT4ZVwgIm2xqF8nvDKHMHIkJxA7FQlj8cBJjFrNnq5jHHU0ILUwQjY8w51vvG00ZA1zSf4w5NrNUS8SAM4I6yWjLdBLmVhzZ5sML/eNJa7rkqmJVamw5lxYngSFUMIrSqk/7ELz1eShlcH03KvmuIXn9ASOlyd5FwuM+U+xEaKyO0WHe+3VP2/jXFgZN9H92TIE/AYh5J2REKpFtfdK/3u1DUPYP6NbCOg7b8bCBQdYJhAcikCjntrtY6rju3yM1W8T1ZQlTg+oH7GC20gL9zNskIjYfcBmAdsRRRaJKTtH+PJmC0FjYxlar8E7DSJDjb/bWEiwSIuaOtUBb68/SLurgj/zX/Xeh8KUEH+hta6CgkB8QCDWOiAHkuvl0EgS0yBFgpv7/itGpaoEsXZBceC5jqYb4udsmd8H2OuxSbpeOwmKrn3Jno/het3FM+5UWelaR+4wnB1dNVXqZSMLFerQWC6xRYZyP9E3t6pev2Uomehb/mW13VJ82UBb/dh7OYPWLv7t9tPFQ/6w5IjViy3viTtQNh6urbAVXqrzzQDbw3jLVBYQJUrH29BuCI9R/l10RLFa11T4pYrJpxZOPtEB6WDnwOYBaVlYWrZKhFfJnOSBqxXrM794sTuffh8Ok/hIuAl0B7aS0R64RMw0EOxT2A+8t2uqYxWsCCMo1m5xNr1bp0kFs/ixjLZ4Ya7+HIR4Zv8OPhjyBCnsNexj6X/tvCr80mBOSAY3QUs0PNCEY=
  template:
    metadata:
      creationTimestamp: null
      name: testgrid-postgres
      namespace: default
status: {}

