apiVersion: v1
kind: Service
metadata:
  name: testgrid-web
  labels:
    app: testgrid-web
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: http
    nodePort: 30881
  selector:
    app: testgrid-web
